version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-password_manager}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-password_manager}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: your-secret-key-here
      DEBUG: True
      SESSION_COOKIE_SECURE: False
    depends_on:
      - db
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: ["./wait-for-it.sh", "db", "5432", "--", "python", "app.py"]
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
