services:
  - type: web
    name: gerenciador-senhas
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: POSTGRES_DB
        value: gerenciador
      - key: POSTGRES_USER
        value: usuario
      - key: POSTGRES_PASSWORD
        value: senha123
      - key: POSTGRES_HOST
        value: localhost
      - key: POSTGRES_PORT
        value: 5432
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: False
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: PYTHONUNBUFFERED
        value: 1
